env:
    node: true
    mocha: true
extends: 'eslint:recommended'
parserOptions:
    ecmaVersion: 8
    sourceType:
        - script
globals:
    getFactory: true
    getSerializer: true
    getAssetRegistry: true
    getParticipantRegistry: true
    getCurrentParticipant: true
    post: true
    emit: true
rules:
    semi:
        - error
        - always
    no-unused-vars:
        - 0
        - args: none
    no-console: off
    curly: error
    eqeqeq: error
    no-throw-literal: error
    strict: error
    dot-notation: error
    no-useless-call: error
    no-with: error
    operator-linebreak: error
    yoda: error
    no-confusing-arrow: 2
    no-constant-condition: 2
